name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            exe: magicvision
            archive: tar.gz

          - os: macos-latest
            exe: magicvision
            archive: tar.gz

          - os: windows-latest
            exe: magicvision.exe
            archive: zip

    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    env:
      RUST_BACKTRACE: 1
      OPENCV_VERSION: 5.0.0
      PKG_CONFIG_ALLOW_CROSS: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      #########################################
      # OpenCV
      #########################################

      - name: Setup OpenCV
        uses: ./.github/actions/opencv
        with:
          version: 5.0.0

      #########################################
      # Build
      #########################################

      - name: Build
        run: cargo build --release

      #########################################
      # Package
      #########################################

      - name: Package (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir release
          cp target/release/magicvision release/
          cp target/release/refresh-database release/
          cp README.md LICENSE release/

          tar czf magicvision-${{ github.ref_name }}-${{ runner.os }}.${{ matrix.archive }} -C release .

      - name: Package (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          mkdir release

          Copy-Item target\release\magicvision.exe release\

          Copy-Item target\release\refresh-database.exe release\

          Copy-Item README.md release\

          Copy-Item LICENSE release\

          $dlls = Get-ChildItem C:\tools\opencv\build\x64 -Recurse -Filter "opencv_world*.dll"

          if (-not $dlls) {
            throw "No OpenCV DLLs found."
          }

          Write-Host "Copying OpenCV DLLs:"
          $dlls | ForEach-Object {
            Write-Host "  $($_.FullName)"
            Copy-Item $_.FullName release\
          }

          Compress-Archive `
            -Path release\* `
            -DestinationPath magicvision-${{ github.ref_name }}-${{ runner.os }}.${{ matrix.archive }}

      #########################################
      # Release
      #########################################

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.zip
